Repository joaolucasMota/ada-devs, pull requests merged in 2023-12, with the labels that each got.

#10 feat-percentual
  calculadora.js
Labels: help wanted

#11 atualização do readme
  .gitignore
  README.md
  calculadora.js
Labels: documentation

#14 Adicionado o método de radiciação
  calculadora.js
Labels: enhancement

#17 Programa salão de beleza
  salao.html
Labels: enhancement
